[package]
name = "rocket-sentry"
version = "0.1.0"
authors = ["Marti Raudsepp <marti@juffo.org>"]
license = "MIT"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sentry = "0.12.0"
rocket = { version = "0.4.2", default-features = false }

[workspace]
members = [
	"example"
]
